services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    user: "$PGUSER"
    volumes:
      - ./container/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    expose:
      - $POSTGRES_PORT
    networks:
      - kreacher
  cache:
    image: redis:7.2.3-alpine3.19
    restart: always
    volumes:
      - ./container/redis:/data
    env_file:
      - ./.env
    command: redis-server --loglevel warning --requirepass $REDIS_PASSWORD
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    expose:
      - $REDIS_PORT
    networks:
      - kreacher
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "6060:80"
    expose:
      - 6060
    networks:
      - kreacher
  app:
    build: .
    restart: always
    depends_on:
      - db
      - cache
    networks:
      - kreacher

networks:
  kreacher:
    driver: bridge

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  pgadmin:
    driver: local
