version: "1"
services:
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  cache:
    image: redis:7.2.1-alpine3.18
    restart: always
    user: root
    volumes: 
      - cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "5050:80"
    expose:
     - 5050
  bot:
    build: .
    depends_on:
      - db
      - cache

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  cache:
    driver: local
